openapi: 3.0.0
info:
  title: NodeBB Write API
  description: >-
    # Overview

    The following document outlines every route exposed by the NodeBB Write API.
    Since NodeBB v1.15.0, NodeBB has used these routes to make changes to the database
    (e.g. creating new posts, editing user profiles, etc.)

    v3 of the Write API (this document) supersedes v2 of the Write API plugin.
  version: 3.0.0
  contact:
    email: support@nodebb.org
  license:
    name: GPL-3.0

servers:
  - url: /api/v3

tags:
  - name: utilities
  - name: users
  - name: groups
  - name: categories
  - name: topics
  - name: posts
  - name: chats
  - name: admin
  - name: files

paths:
  /ping:
    $ref: 'write/ping.yaml'

  /utilities/login:
    $ref: 'write/login.yaml'

  /users/:
    $ref: 'write/users.yaml'

  /users/{uid}:
    $ref: 'write/users/uid.yaml'

  /users/{uid}/picture:
    $ref: 'write/users/uid/picture.yaml'

  /users/{uid}/content:
    $ref: 'write/users/uid/content.yaml'

  /users/{uid}/account:
    $ref: 'write/users/uid/account.yaml'

  /users/{uid}/status:
    $ref: 'write/users/uid/status.yaml'

  /users/{uid}/status/{status}:
    $ref: 'write/users/uid/status/status.yaml'

  /users/{uid}/chat:
    $ref: 'write/users/uid/chat.yaml'

  /users/{uid}/settings:
    $ref: 'write/users/uid/settings.yaml'

  /users/{uid}/password:
    $ref: 'write/users/uid/password.yaml'

  /users/{uid}/follow:
    $ref: 'write/users/uid/follow.yaml'

  /users/{uid}/ban:
    $ref: 'write/users/uid/ban.yaml'

  /users/{uid}/mute:
    $ref: 'write/users/uid/mute.yaml'

  /users/{uid}/tokens:
    $ref: 'write/users/uid/tokens.yaml'

  /users/{uid}/tokens/{token}:
    $ref: 'write/users/uid/tokens/token.yaml'

  /groups/:
    $ref: 'write/groups.yaml'

  /groups/{slug}:
    $ref: 'write/groups/slug.yaml'

  /categories/:
    $ref: 'write/categories.yaml'

  /categories/{cid}:
    $ref: 'write/categories/cid.yaml'

  /topics/:
    $ref: 'write/topics.yaml'

  /topics/{tid}:
    $ref: 'write/topics/tid.yaml'

  /topics/{tid}/state:
    $ref: 'write/topics/tid/state.yaml'

  /topics/{tid}/lock:
    $ref: 'write/topics/tid/lock.yaml'

  /topics/{tid}/pin:
    $ref: 'write/topics/tid/pin.yaml'

  /topics/{tid}/follow:
    $ref: 'write/topics/tid/follow.yaml'

  /topics/{tid}/ignore:
    $ref: 'write/topics/tid/ignore.yaml'

  /topics/{tid}/tags:
    $ref: 'write/topics/tid/tags.yaml'

  /topics/{tid}/thumbs:
    $ref: 'write/topics/tid/thumbs.yaml'

  /topics/{tid}/read:
    $ref: 'write/topics/tid/read.yaml'

  /topics/{tid}/move:
    $ref: 'write/topics/tid/move.yaml'

  /topics/{tid}/resolved:
    put:
      tags:
        - topics
      summary: Mark topic as resolved or unresolved
      parameters:
        - name: tid
          in: path
          required: true
          example: 1
          schema:
            type: number
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              example:
                resolved: 1
              properties:
                resolved:
                  type: number
                  description: Whether the topic is resolved (0 = no, 1 = yes)
      responses:
        "200":
          description: Topic resolved state updated
          content:
            application/json:
              schema:
                $ref: "components/schemas/CommonProps.yaml#/CommonProps"
        "400":
          description: Invalid request




  /posts/{pid}:
    $ref: 'write/posts/pid.yaml'

  /posts/{pid}/raw:
    $ref: 'write/posts/pid/raw.yaml'

  /posts/{pid}/summary:
    $ref: 'write/posts/pid/summary.yaml'

  /posts/{pid}/state:
    $ref: 'write/posts/pid/state.yaml'

  /posts/{pid}/vote:
    $ref: 'write/posts/pid/vote.yaml'

  /chats/:
    $ref: 'write/chats.yaml'

  /chats/{roomId}:
    $ref: 'write/chats/roomId.yaml'

  /admin/settings/{setting}:
    $ref: 'write/admin/settings/setting.yaml'

  /admin/analytics:
    $ref: 'write/admin/analytics.yaml'

  /files/:
    $ref: 'write/files.yaml'
